### ISSUE TITLE
Add Mayastor data plane network bind to dedicated NIC

### ISSUE THREAD

**Issue by silverhandy** [openebs/mayastor#1126]
**Is your feature request related to a problem? Please describe.**
We have two NICs, one plan for storage network (OpenEBS), another plan for service application.
if we want to bind the mayastor dataplane with the NIC for storage network, how can I do it?
I saw the configs in mayastor-daemonset.yaml as following, but sure how to set the dedicated NIC with ip range.

mayastor-daemonset.yaml:
   spec:
      hostNetwork: true
      # To resolve services from mayastor's namespace
      dnsPolicy: ClusterFirstWithHostNet

**Describe the solution you'd like**
we can set hostNetwork: true and set mayastor daemonset configmap to IP/subnetwork for a NIC/VF.
The Mayastor network can separate with application service network.

**Describe alternatives you've considered**
OpenEBS Mayastor network based on SRIOV/Multus CNI.

**Additional context**
N/A

**Comment by kpoos** [comment]
Looks like the same as : https://github.com/openebs/mayastor/issues/1048
This really a critical thing. It should be able to use separate networks...

**Comment by GlennBullingham** [comment]
@silverhandy @kpoos Thank you for your input and suggestion.  I hope you won't mind if I ask some clarifying questions.

Question 1:  _Why_ do you consider this to be a 'critical' requirement?  What is your primary driver for storage network segregation?  Is it a matter of:

- performance/latency - QoS, rate limiting, reserved BW etc.?
- security?
- availability?
- all of the above / something else ?

Question 2: On the face of it , any solution appears (to me, at least) to be very tightly coupled with the CNI implementation that you intend to use.  If we made this feature available, which _one_ do you think we should choose to support?  Multus?  DANM?

**Comment by kpoos** [comment]
Actually if you have separate NIC for storage on node level, which is quite often used in on-prem data center solutions, you need to set up mayastor not to use the cluster networking but to use the other data channel on the second nic. In our solution - which was prior mayastor v1.0 - I just changed the data plane (mayastor) and the mayastor-csi pods command lines with overwriting the the MY_NODE_NAME / MY_POD_IP env vars (which is in that case was the node IP as it runs in hostNetwork: true mode, so I was able to get  mayastor listen on the 2nd interface, while all the other communication goes in the k8s network. In our case this is needed, as the storage network has 10G interfaces and the normal network has only 1G interfaces. 
I would say, it is mostly performance related, however a separate storage network is good to have in security and availability point of view as well.  
I think, in such a case - when you synch data over the network - it is mandatory to have a selectable interface on the binary, which is used for data communication in cases when you have several interfaces on node level.
As I previously said, it is nothing to do with the CNI, because these components run in the host network. It is just should be one parameter, to say to the binary, which network interface/IP to use for the data communication on the data plane layer, mostly for volume resynchronization. The other communication which is taken place in the k8s cluster networking can remain in the normal way as it is.

**Comment by GlennBullingham** [comment]
Thanks.  Good points, well made.  For 'supported', I should have really said 'tested'.  _If_ there were an early consensus on likely use-case(s), this might help guide the selection of system test environment(s) where it comes to that functionality, for anyone wishing to contribute to it (the maintainers included).

**Comment by gila** [comment]
The code where the listen address is determined is in `subsys/nvmf/target.rs` Currently; it grabs whatever `get_ipv4_address()` returns. This was done very early during the development of mayastor and very limited indeed. 

A proper approach would be to add appropriate gRPC methods to add and/or remove listeners on the fly and perhaps a new ENV (for easy deployment) which would accept a list of IP & port tuples (separated by `;`).  The latter in particular is pretty trivial to do. @valkolaci if you want to draft the patches I'd be happy to review them.

**Comment by GlennBullingham** [comment]
This feature (ability to define target port binding on the basis of subnet, interface name or specific IP address) has been implemented and is currently in test.

Targeting version 2.0.0, which is currently expected to be released within the next 30-60 days.

**Comment by Daxcor69** [comment]
do we have an updated release date on this feature?

**Comment by GlennBullingham** [comment]
@Daxcor69 We're still targeting this for Mayastor 2.0.  Provisionally, we're looking at early to mid-September for that release, based on current progress.

**Comment by GlennBullingham** [comment]
The changes for this feature have already been merged into the develop branch.  

In lieu of formal documentation at this time, the implementation chosen was to add the argument `--tgt-iface` to the mayastor binary (the environment variable `NVMF_TGT_IFACE` may be set instead, if preferred.)

Usage:
`--tgt-iface ip:127.0.0.1` : binds the target to the specified IPv4 address
`--tgt-iface subnet:1.2.3.4/24` : binds to the IPv4 address which matches the specified subnet mask (CIDR notation)
`--tgt-iface mac:00:12:5c:74:2d:cd` : binds to the IPv4 address of the interface with the specified MAC address
`--tgt-iface name:eth0` : binds to the IPv4 address of the interface with the specified name

If a match cannot be made the mayastor container will terminate.  For the official release, this configurable parameter will be included in the Helm chart's values.yaml file.
