### ISSUE TITLE
allocated 2M hugepages, but 1G used during init

### ISSUE THREAD

**Issue by luginbash** [openebs/mayastor#1133]
**Describe the bug**
mayastor deteced 1024x 2M hugepages, but tries to reserve hugepages of size 1073741824, causing failure.

**To Reproduce**

1. find a node supports multiple hugepage pools
2. snap install microk8s  from edge channel
3. microk8s enable core/mayastor
4. kubectl -n mayastor get pods <--- id the failing mayastor-$ID pod
5. get logs

**Expected behavior**
Ready 

**Screenshots**
```
> kubectl -n mayastor logs --since=2m mayastor-t278c
[2022-05-11T04:54:55.812470509+00:00  INFO mayastor:mayastor.rs:94] free_pages: 1024 nr_pages: 1024
[2022-05-11T04:54:55.812531636+00:00  INFO mayastor:mayastor.rs:133] Starting Mayastor version: v1.0.0-119-ge5475575ea3e
[2022-05-11T04:54:55.812597744+00:00  INFO mayastor:mayastor.rs:134] kernel io_uring support: yes
[2022-05-11T04:54:55.812610107+00:00  INFO mayastor:mayastor.rs:138] kernel nvme initiator multipath support: yes
[2022-05-11T04:54:55.812632989+00:00  INFO mayastor::core::env:env.rs:600] loading mayastor config YAML file /var/local/mayastor/config.yaml
[2022-05-11T04:54:55.812652179+00:00  INFO mayastor::subsys::config:mod.rs:168] Config file /var/local/mayastor/config.yaml is empty, reverting to default config
[2022-05-11T04:54:55.812668723+00:00  INFO mayastor::subsys::config::opts:opts.rs:155] Overriding NVMF_TCP_MAX_QUEUE_DEPTH value to '32'
[2022-05-11T04:54:55.812687806+00:00  INFO mayastor::subsys::config:mod.rs:216] Applying Mayastor configuration settings
EAL: 4 hugepages of size 1073741824 reserved, but no mounted hugetlbfs found for that size
EAL: alloc_pages_on_heap(): couldn't allocate memory due to IOVA exceeding limits of current DMA mask
EAL: alloc_pages_on_heap(): Please try initializing EAL with --iova-mode=pa parameter
EAL: error allocating rte services array
EAL: FATAL: rte_service_init() failed
EAL: rte_service_init() failed
thread 'main' panicked at 'Failed to init EAL', mayastor/src/core/env.rs:543:13
stack backtrace:
   0: std::panicking::begin_panic
   1: mayastor::core::env::MayastorEnvironment::init
   2: mayastor::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

** OS info (please complete the following information):**
 - Distro: Ubuntu
 - Kernel version: Linux $(hostname) 5.16.0-0.bpo.4-amd64 #1 SMP PREEMPT Debian 5.16.12-1~bpo11+1 (2022-03-08) x86_64 GNU/Linux
 - MayaStor revision or container image v1.0.0-119-ge5475575ea3e inside 1.0.1-microk8s-1

**Additional context**

**Comment by luginbash** [comment]
This looks like a dupe of #494 , but that one was closed without any progress.

**Comment by tiagolobocastro** [comment]
Hi @luginbash, we don't really test on microk8s AFAIK.
I'm trying to set it up on a VM, but this doesn't seem to do anything:
```
tiago@vmt:~$ microk8s enable core/mayastor
Nothing to do for `core/mayastor`.
```
Any clues on why I might be missing?

**Comment by lopesdasilva** [comment]
@tiagolobocastro you need to switch the channel to the version 1.24+
e.g.
`sudo snap install microk8s --classic --channel=1.24/stable`

**Comment by gila** [comment]
Are we sure that rte_eal_init() does the right thing? i.e try either 2MB pages and if not found try 1GB pages? When I wrote the code -- back in the day, I recall the need to pass the page size explicitly.

**Comment by stygmate** [comment]
any news on this one ? (i'm stuck installing a microk8s cluster on baremetal servers because of this one)

**Comment by luginbash** [comment]
Just tried with latest everything, and got

```lug@sin9 ~> microk8s.kubectl logs -n mayastor  mayastor-cnnd9
Defaulted container "mayastor" out of: mayastor, registration-probe (init), etcd-probe (init), initialize-pool (init)
[2022-06-02T03:31:28.271337047+00:00 ERROR mayastor:mayastor.rs:84] insufficient free pages available PAGES_NEEDED=1024 nr_pages=1024```
error gets a bit more vague.

**Comment by robert83ft** [comment]
```
io-engine
[2022-06-04T10:01:07.170524572+00:00 INFO io_engine:io-engine.rs:132] Engine responsible for managing I/Os version 1.0.0, revision a6424b565ea4 (v1.0.0)
io-engine
thread 'main' panicked at 'failed to read the number of pages: Os { code: 2, kind: NotFound, message: "No such file or directory" }', io-engine/src/bin/io-engine.rs:74:10
io-engine
stack backtrace:
io-engine
0: rust_begin_unwind
io-engine
at ./rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
io-engine
1: core::panicking::panic_fmt
io-engine
at ./rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
io-engine
2: core::result::unwrap_failed
io-engine
at ./rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1617:5
io-engine
3: io_engine::hugepage_get_nr
io-engine
4: io_engine::main
io-engine
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Obivously huge pages are enabled: 

```
[root@centos /]# grep HugePages /proc/meminfo
HugePages_Total:    2048
HugePages_Free:     2033
HugePages_Rsvd:        9
HugePages_Surp:        0
```

**Comment by robert83ft** [comment]
I passed this issue by adding :  

```
        resources:
          limits:
            ....
            hugepages-1Gi: {{ .Values.mayastor.resources.limits.hugepages1Gi | quote }}
          requests:
            .... 
            hugepages-1Gi: {{ .Values.mayastor.resources.limits.hugepages1Gi | quote }}
```

in io-engine-daemonset.yaml

And corresponding : 

```
    requests:
      ...
      hugepages1Gi: "2Gi"
```
in values.yaml.

Now back to 

`60 - EAL: 2 hugepages of size 1073741824 reserved, but no mounted hugetlbfs found for that size
59 - EAL: alloc_pages_on_heap(): couldn't allocate memory due to IOVA exceeding limits of current DMA mask
58 - EAL: alloc_pages_on_heap(): Please try initializing EAL with --iova-mode=pa parameter
57 - EAL: error allocating rte services array
56 - EAL: FATAL: rte_service_init() failed
55 - EAL: rte_service_init() failed
54 - thread 'main' panicked at 'Failed to init EAL', io-engine/src/core/env.rs:556:13`

**Comment by tiagolobocastro** [comment]
@robert83ft, what happens if you try adding "--env-context='--iova-mode=pa'" to the mayastor container arguments?

**Comment by robert83ft** [comment]
@tiagolobocastro Eventually I solved it without the changing "iova-mode" to pa. I found that the io-engine deployment (yaml) is missing a volume mounted. It's declared but not mounted.

![Screenshot from 2022-06-11 21-14-30](https://user-images.githubusercontent.com/7677543/173200092-487631ae-c2ce-492b-9c9d-4e367540a899.png)

When I made the last change that helped (above) I still had both 2M and 1G hugepages on node enabled. My default is 2M. I learned that when 2 types of hugepages are enabled mounts should be differentiated

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/virtualization_tuning_and_optimization_guide/sect-virtualization_tuning_optimization_guide-memory-huge_pages-1gb-runtime

however my running setup now only has single mount in io-engine deployment. This seems to suggest it does start now with 2M only. I'm will probably roll-back my nodes to 2M only and try to confirm.

**Comment by brentgroves** [comment]
Using microk8s and mayastor addon on 3 nodes which are each running ubuntu 22.04.
followed these instructions https://microk8s.io/docs/addon-mayastor
And Noticed I almost had enough free pages so I decided to change the suggested:
sudo sysctl vm.nr_hugepages=1024
echo 'vm.nr_hugepages=1024' | sudo tee -a /etc/sysctl.conf
to: 
sudo sysctl vm.nr_hugepages=1048
echo 'vm.nr_hugepages=1048' | sudo tee -a /etc/sysctl.conf
sudo nvim /etc/sysctl.conf

and that seemed to do the trick.

**Comment by 0dragosh** [comment]
I've added the sysctl and can verify that vm.nr_hugepages is 1024 and I still get the same error. Restarted kubelet and all the nodes multiple times.

**Comment by DelayLama** [comment]
Good evening from Germany, folks!

It's the 26th of November in 2024, im running bleeding edge microk8s v1.31.3 on three bare metal Ubuntu 24.04 nodes with 16 GB RAM each and I'm running in exactly the same trap aka problem. Seems like this rock hasn't been moved in a long time and I found no documented solution for this. But I'm currently noit willing to give up.

I've got 28 years of linux epericence, I've been an Ubuntu user and contributor right from the start in 2004, but I'm completely new to kubernetes and microk8s, so please forgive me if I'm lacking experience here ins this niche.

I'm trying to setup up a microk8s cluster with clustered mayastore in HA mode because my ADHD brain is bored and I need to learn something new to feed my curiosity - and I opted for microk8s because why not, I certainly won't get any dumber from this.

So, introduction aside, I need help. Has anybody been able to figure out what to do about this?
And if not- is anyone willing to partner up and fight through this together?

Many greetings from Wiesbaden,
Mathias

**Comment by jrepp** [comment]
The problem here is a problem using the underlying Intel `spdk_env_dpdk_rte_eal_init` on certain systems.

A fix that allows the nodes to come up is to use physical adressing instead of DMA for the huge pages mapped by the underlying data platform SDK:

Use kubectl to change the arguments of the launched io engine container to include --env-context which will be passed to the underlying API.

`daemonset.apps/mayastor-io-engine`
```yaml
  containers:
      - args:
        - -g$(MY_POD_IP)
        - -N$(MY_NODE_NAME)
        - -Rhttps://mayastor-agent-core:50051
        - -y/var/local/io-engine/config.yaml
        - -l1,2
        - -p=etcd-client:2379
        - --ptpl-dir=/var/local/io-engine/ptpl/
        - --api-versions=v1
        - --env-context=--iova-mode=pa
```

I appears that mayastor wants to have a lot of pages (I tried 1024, 2048 and finally 1048). I think the issue may be that when the page size is too large you can't map this memory using DMA depending on your kernel, hardware, etc. I didn't dig into this as I don't care about DMA performance for my use case currently.

` EAL: alloc_pages_on_heap(): couldn't allocate memory due to IOVA exceeding limits of current DMA mask `

See:
https://github.com/openebs/mayastor/blob/develop/io-engine/src/core/env.rs

In my case I'm using MicroK8S snap on Ubuntu 24 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz with 128Gb of memory.

When enabling huge pages the default page size is 2MB

`cat /proc/meminfo|grep Huge`
```
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
FileHugePages:         0 kB
HugePages_Total:    1048
HugePages_Free:      548
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:         2146304 kB
```
