### ISSUE TITLE
pool worker in error

### ISSUE THREAD

**Issue by simcax** [openebs/mayastor#1137]
**Describe the bug**
After restarting a node the pool worker on the node is in error. 

**To Reproduce**
Get a cluster running with 3 pool workers, reboot one node.

**Expected behavior**
The restarted node rejoin the pool and data is updated in case of multiple replicas

**Screenshots**
~ kubectl mayastor get nodes
 ID               GRPC ENDPOINT        STATUS 
 talos-worker-03  172.20.20.153:10124  Online 
 talos-worker-04  172.20.20.154:10124  Online 
 talos-worker-05  172.20.20.155:10124  Online 

➜  ~ kubectl -n mayastor get msp
NAME             NODE              STATUS   CAPACITY      USED          AVAILABLE
pool-worker-03   talos-worker-03   Error    0             0             0
pool-worker-04   talos-worker-04   Online   53632565248   27917287424   25715277824
pool-worker-05   talos-worker-05   Online   53632565248   27917287424   25715277824

** OS info (please complete the following information):**
Talos Linux 1.0
Kernel: 5.15.32
Kubernetes: 1.23.5
MayaStor: v1.0.1 

**Additional context**
I have previously had trouble with getting all etcd nodes to run, but all pods are now runnning. 
The msp-operator has this error in the log:
msp-operator   May 15 17:32:55.777  INFO msp_operator: CRD present                                                                        │
│ msp-operator     at control-plane/msp-operator/src/main.rs:807                                                                            │
│ msp-operator                                                                                                                              │
│ msp-operator   May 15 17:32:55.785  INFO msp_operator: Starting Mayastor Pool Operator (MSP) in namespace mayastor                        │
│ msp-operator     at control-plane/msp-operator/src/main.rs:923                                                                            │
│ msp-operator                                                                                                                              │
│ msp-operator   May 15 17:32:56.022 ERROR msp_operator: entered error as final state, pool: "pool-worker-03"                               │
│ msp-operator     at control-plane/msp-operator/src/main.rs:880                                                                            │
│ msp-operator     in msp_operator::reconcile with name: talos-worker-03, status: Some(MayastorPoolStatus { state: Error, capacity: 0, used │
│ msp-operator     in kube_runtime::controller::reconciling object with object.ref: MayastorPool.v1alpha1.openebs.io/pool-worker-03.mayasto │
│ msp-operator 

How would I go about getting that error sorted?

**Comment by hiattp** [comment]
@simcax How did you end up resolving this issue? I'm seeing the same problem. Thanks!

**Comment by tiagolobocastro** [comment]
Do you have a pool in error state @hiattp? You can try to delete it and recreate it, if that doesn't work then we'll probably need to collect some logs/etc.

**Comment by hiattp** [comment]
Hey @tiagolobocastro yeah I did, I was updating from talos linux 1.2.4 to 1.3.0 which involved several node restarts. After the series of updates and restarts all of my pools were in an error state and pods on related PVCs wouldn’t initialize (volume not found errors or something to that effect). To be fair in production presumably we would have only upgraded one node at a time, then ensured the mayastor replicas survived or would have restored them before losing the other replicas. Instead I bulk updated all nodes simultaneously and they were all rebooting (and erroring out) at the same time. 

Does deleting and recreating the pool wipe the volume? Since all replicas were erroring out I was reluctant to do that. This is just a test setup (I’m evaluating mayastor) so I ended up just killing all storage classes/volumes/pools and uninstalling mayastor, I’m going to try installing mayastor v2 (this was on v1) and then will see if I can reproduce. But curious to know what troubleshooting/recovery would have looked like, particularly whether the only way to resolve was deleting and reinitializing the pools and whether that loses data. Disaster recovery is one of the things I’m trying to evaluate. Thanks!

**Comment by tiagolobocastro** [comment]
> Does deleting and recreating the pool wipe the volume

No it doesn't, the control-plane will not delete pools that have replicas. If you remove the finaliser and delete the CR, the actual pool will be untouched if it has any replicas.
Conversely creating the pool again will not delete the existing data, rather it would either fail (if the pool name is different) or it will simply be an "import".

The issue you're probably hitting is probably that the pool operator is too eager to reconcile the CR's into a sticky error state. The actual pool might be fine, which you can query by using the kubectl-plugin, example: `kubectl-mayastor get pools`. 
On the current `develop` that behaviour is a bit better but there is still one case where pool CR's go into error and don't recover, we hope to fix that soon.

kubectl-mayastor get nodes, kubectl-mayastor get pools, kubectl-mayastor get volumes is probably the first starting point to start troubleshooting.
On `develop` we also have a kubectl-mayastor dump system to collect a support-bundle with all sorts of information.

**Comment by hiattp** [comment]
Ok that all sounds great, thanks! I’ll give it a try on v2 and resurface here if I hit an unresolvable error. Appreciate the responsiveness!

**Comment by simcax** [comment]
> @simcax How did you end up resolving this issue? I'm seeing the same problem. Thanks!

@hiattp - I ended up abondoning mayastor, as I unfortunately couldn't get it to work. The issue at the time was most likely number of CPU cores available. I now have a new homelab server, which is spec'ed a lot better, but haven't had time to get back to this project yet.
