### ISSUE TITLE
[Doc Source]: [Upgrades and Reboots]

### ISSUE THREAD

**Issue by Trolldemorted** [openebs/mayastor#1145]
**Are you reporting an issue with existing content?**
The documentation unambiguously states that mayastor needs at least three nodes:

>As of version 1.0 the minimum supported worker node count is three nodes.

But it does not mention what exactly happens if one becomes unavailable. How does one update mayastor clusters with just 3 nodes? Furthermore [this scenario](https://mayastor.gitbook.io/introduction/reference/replica-operations#scenario-one) only mentions 2 nodes, is that outdated?

**Are you proposing new content, or a change to the existing documentation layout or structure?**
The documentation should describe how to facilitate mundane server maintenance tasks:

- A new mayastor update is released, and the cluster should be upgraded without breaking anything.
- In a cluster of 3 nodes, all nodes need to reboot because of a Linux kernel update. From the insights we gained through #1142 we assume that preventing all disk writes and rebooting them one after the other should work, but it should be documented if it is the case :)

**Comment by GlennBullingham** [comment]
Thanks @Trolldemorted.  Your suggestions will be incorporated in the documentation and release notes for the next release.

To provide some brief answers here:

- 3 nodes is the minimum recommended deployment, since it provides a level of control plane redundancy in the event of a single node loss
- If one node is lost (2 remaining) control plane operations can continue as expected.  If a further node is lost, control plane functionality will degrade (e.g. provisioning of new volumes will become impossible, active volumes will not be republished if needed)
- The only "supported" upgrade pattern as of the current release (v1.0.1) is "cold and dark"; the Mayastor data plane should not  have any active targets (i.e. no volumes published) and the control plane should not be running
- Non-disruptive ("hot") upgrade capability (application I/O unaffected) is being implemented at this time and will be introduced in a future release (targeting a version later than 2.0.0)
- A future release of Mayastor (forward of 2.0.0) will include lifecycle management features, e.g. node cordon, drain and target failover, to facilitate planned hardware and software maintenance activities.
