### ISSUE TITLE
Roadmap doc for mayastor? Would be useful to have documentation page that tracks the state of different mayastor features

### ISSUE THREAD

**Issue by PaulCapestany** [openebs/mayastor#1190]
As the title states, it'd be useful to have a documentation page that tracks the state of different mayastor features.

For example, the 2 main things I'd be curious about are the status of these 2 ["Known Limitations"](https://mayastor.gitbook.io/introduction/quickstart/known-limitations): 
- `Volume and Pool Capacity Expansion`
- `Volumes are "Highly Durable" but without multipathing are not "Highly Available"`
 
I did some grepping through some of the relevant repos but I'm not familiar enough yet with the project (or Rust) to easily figure out where things are at—how far along are these features, and/or should a "roadmap" doc be put together for those who might have similar technically-important feature status questions?

**Comment by GlennBullingham** [comment]
Great suggestion @PaulCapestany.  We've been a little remiss up until now when it comes to surfacing that kind of information with the community but there's work currently in progress to deliver an update to the OpenEBS roadmap which includes the kinds of information you're suggesting w.r.t. Mayastor.  I'm expecting it to be published in the next few days - I'll circle back here with an update and link once we're done.

However, to give you some quick feedback on the particular areas you raised:

- Volume expansion: The maintainers will be looking into specifications and potential high level designs for this shortly, with a view to delivering _something_ in Q4 this year.  At the moment, we're unsure whether this would be online or offline expansion.  Suggestions and contributions welcome.

- Pool expansion: With the Blobstor persistence layer this isn't possible right now.  The maintainer's current view is that automated capacity management on a cluster-wide basis (disk pool lifecycle management, moving replicas between pools, flexing replica counts within preset limits, thin-provisioning etc.) is the approach that we'll take, rather than providing for the expansion of a pool.  We're thinking to favour automated management of capacity at the cluster level, rather than reliance on users needing to manage it at the pool level, especially where the node/pool/volume count is very high.

- Providing high availability for volume targets (e.g. loss / restart of a Mayastor io pod) is currently work in progress and we expect to have a MVP implementation available for release towards November.  Design documentation for this work will be transferred to the Mayastor repo during this month.

**Comment by avishnu** [comment]
Thanks @PaulCapestany.
We have traditionally maintained the roadmap of the various engines under OpenEBS [here](https://github.com/openebs/openebs/blob/main/ROADMAP.md)
Please track this [PR](https://github.com/openebs/openebs/pull/3569) for the latest updates on Mayastor features.

**Comment by laibe** [comment]
+1 for high availability for volume targets, this would be really great to have!

**Comment by tiagolobocastro** [comment]
@laibe that is now part of the product.
Roadmap on openebs/openebs now tracks the mayastor engine.
