### ISSUE TITLE
Mayastor just plainly does not start under Microk8s 1.24/stable

### ISSUE THREAD

**Issue by victor-sudakov** [openebs/mayastor#1204]
**Describe the bug**
Multiple pods in the mayastor namespace just stuck in the pending state. No mayastorpool ever becomes ready.

**To Reproduce**
- Preconfigure 4 Debian11 machines as stated in https://microk8s.io/docs/addon-mayastor (huge pages, kernel modules).
- `snap install microk8s --classic --channel=1.24/stable` on the 4 machines
- Join the 4 nodes into one cluster with `microk8s.add-node`, verify that the HA cluster is up with `microk8s.status`
- Try to enable the core/mayastor addon as stated in https://microk8s.io/docs/amicrok8s.add-nodeddon-mayastor, with a 6G default pool size.

**Expected behavior**
The mayastor operator should start, the 6G pool should become available.

**Screenshots**
![microk8s](https://user-images.githubusercontent.com/12457866/191892620-7b4d2426-d8a4-4954-b2a4-091c03a442f5.png)

** OS info (please complete the following information):**
 - Distro: Debian 11 bullseye
 - Kernel version: 5.10.0-18-cloud-amd64
 - MayaStor revision or container image: stock from microk8s 1.24

**Additional context**
I am so overwhelmed by so many containers pending, I don't even know whose logs to show and where to start debugging. The microk8s cluster seems operational otherwise:
```
# /snap/bin/microk8s.kubectl get nodes
NAME            STATUS   ROLES    AGE   VERSION
vas-k3s-test4   Ready    <none>   18h   v1.24.4-2+2f38f78fa07274
vas-k3s-test3   Ready    <none>   18h   v1.24.4-2+2f38f78fa07274
vas-k3s-test1   Ready    <none>   18h   v1.24.4-2+2f38f78fa07274
vas-k3s-test2   Ready    <none>   18h   v1.24.4-2+2f38f78fa07274
```

If this is a microk8s issue and not a mayastor issue, please redirect me to their bug tracker.

**Comment by victor-sudakov** [comment]
Just picking randomly into some pending pods, the check-dns container:

![image](https://user-images.githubusercontent.com/12457866/191893570-c388156b-2190-4eb0-8fc3-07b556c323c3.png)

**Comment by victor-sudakov** [comment]
Here is what it prints when I enable the addon:

```
# /snap/bin/microk8s.enable core/mayastor --default-pool-size 6G
Checking for HugePages (>= 1024)...
Checking for HugePages (>= 1024)... OK
Checking for nvme_tcp module...
Checking for nvme_tcp module... OK
Checking for addon core/dns...
Checking for addon core/dns... OK
Checking for addon core/helm3...
Checking for addon core/helm3... OK
Error from server (AlreadyExists): namespaces "mayastor" already exists
Default image size set to 6G
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /var/snap/microk8s/3719/credentials/client.config
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://raw.githubusercontent.com/canonical/mayastor-control-plane/develop/chart" chart repository
...Successfully got an update from the "https://raw.githubusercontent.com/canonical/mayastor/develop/chart" chart repository
...Successfully got an update from the "https://raw.githubusercontent.com/canonical/etcd-operator/master/chart" chart repository
Saving 3 charts
Downloading etcd-operator from repo https://raw.githubusercontent.com/canonical/etcd-operator/master/chart
Downloading mayastor from repo https://raw.githubusercontent.com/canonical/mayastor/develop/chart
Downloading mayastor-control-plane from repo https://raw.githubusercontent.com/canonical/mayastor-control-plane/develop/chart
Deleting outdated charts
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /var/snap/microk8s/3719/credentials/client.config
NAME: mayastor
LAST DEPLOYED: Thu Sep 22 23:38:04 2022
NAMESPACE: mayastor
STATUS: deployed
REVISION: 1
TEST SUITE: None

=============================================================

Mayastor has been installed and will be available shortly.

Mayastor will run for all nodes in your MicroK8s cluster by default. Use the
'microk8s.io/mayastor=disable' label to disable any node. For example:

    microk8s.kubectl label node vas-k3s-test3 microk8s.io/mayastor=disable

```
But its pods never really come up.

**Comment by GlennBullingham** [comment]
@victor-sudakov To be honest, I'm not sure what the root cause is based on the above but, given the failure to resolve the service name of the etcd instance you've shown above, I'm fairly certain that many of the other Mayastor pods wouldn't init anyway, since they check for the availability of this service.

For that matter, neither is your etcd pod running.

So, what do you see if you `kubectl describe` the pods that are pending?  Perhaps start with checking why the etcd pod is stuck?

I think a bit of generic k8s troubleshooting is in order here, before going to potential mayastor-specific issues.

**Comment by victor-sudakov** [comment]
> Perhaps start with checking why the etcd pod is stuck?

Does Mayastor bring its own etcd service or does it expect some external one? I may be mistaken but I don't think a default Microk8s installation contains any etcd:

```
# ps axww | grep /snap/microk8s/
 254563 ?        Ss     0:39 /bin/bash /snap/microk8s/3719/apiservice-kicker
 254944 ?        Ssl   57:52 /snap/microk8s/3719/bin/k8s-dqlite --storage-dir=/var/snap/microk8s/3719/var/kubernetes/backend/ --listen=unix:///var/snap/microk8s/3719/var/kubernetes/backend/kine.sock:12379
 255252 ?        Ss     0:00 /bin/bash /snap/microk8s/3719/run-cluster-agent-with-args
 255279 ?        Sl     0:02 /snap/microk8s/3719/bin/cluster-agent --bind 0.0.0.0:25000 --keyfile /var/snap/microk8s/3719/certs/server.key --certfile /var/snap/microk8s/3719/certs/server.crt --timeout 240
 255380 ?        Ssl    9:35 /snap/microk8s/3719/bin/containerd --config /var/snap/microk8s/3719/args/containerd.toml --root /var/snap/microk8s/common/var/lib/containerd --state /var/snap/microk8s/common/run/containerd --address /var/snap/microk8s/common/run/containerd.sock
 255512 ?        Ssl   85:33 /snap/microk8s/3719/kubelite --scheduler-args-file=/var/snap/microk8s/3719/args/kube-scheduler --controller-manager-args-file=/var/snap/microk8s/3719/args/kube-controller-manager --proxy-args-file=/var/snap/microk8s/3719/args/kube-proxy --kubelet-args-file=/var/snap/microk8s/3719/args/kubelet --apiserver-args-file=/var/snap/microk8s/3719/args/kube-apiserver --kubeconfig-file=/var/snap/microk8s/3719/credentials/client.config --start-control-plane=true
 255783 ?        Sl     3:45 /snap/microk8s/3719/bin/containerd-shim-runc-v2 -namespace k8s.io -id 996ce86ce832eef2c90653628b1ee1819c8a6a73e4cd312c52d9b567a58c93dc -address /var/snap/microk8s/common/run/containerd.sock
 256677 ?        Sl     0:37 /snap/microk8s/3719/bin/containerd-shim-runc-v2 -namespace k8s.io -id 6cded02142c29be7c80ad851476ef4a2e77a89d8c1058ce4f5901514d7c3fd0a -address /var/snap/microk8s/common/run/containerd.sock
 928704 pts/0    R+     0:00 grep /snap/microk8s/

```
The cluster uses dqlite as a configuration storage by default.

**Comment by GlennBullingham** [comment]
> Does Mayastor bring its own etcd service or does it expect some external one?

It depends.  If the deployment is made following the example we provide in the official [Mayastor documentation](https://github.com/openebs/mayastor-docs/blob/version/1.0/quickstart/deploy-mayastor.md), then the etcd instance required is deployed at the same time, using a Helm chart prepared by the OpenEBS maintainers.

What is happening in your case, is that the providers of the Canonical Mayastor add-on are providing their own installation route, [using an etcd operator](https://github.com/canonical/microk8s-core-addons/tree/main/addons/mayastor/chart#etcd-operator).

So my suggestion to progress your issue is a) use some basic k8s troubleshooting to ascertain why the etcd pod isn't starting and b) if that isn't down to something directly related to your node setup (i.e. resource shortage), then maybe raise an issue with the [core add-ons community at Canonical ](https://github.com/canonical/microk8s-core-addons/tree/main/addons/mayastor/chart#etcd-operator).

Potentially another option: remove the etcd and etcd-operator deployments and instead deploy etcd on your node [using the directions from the Mayastor documenation](https://github.com/canonical/microk8s-core-addons/tree/main/addons/mayastor/chart#etcd-operator).  If you do that, be sure to scale down the replica count to one in the `statefulset.yaml`

**Comment by victor-sudakov** [comment]
@GlennBullingham Do you suggest I should start debugging with researching why the etcd pod in the mayastor namespace is not starting? I will have time to do it hopefully on Wednesday, we can put this issue on hold till then. Thank you for the hint.

**Comment by GlennBullingham** [comment]
> Do you suggest I should start debugging with researching why the etcd pod in the mayastor namespace is not starting?

Yes, absolutely.  I think that's the correct starting point.

The control and data plane Mayastor pods will not start until they can find their expected etcd instance is available.  And if there's something causing the scheduling of the etcd instance to fail, it may well impact Mayastor pods directly too.

**Comment by victor-sudakov** [comment]
Oh well, the etcd pod is stuck in the PodInitializing state, and its initContainer "check-dns" is failing the check (see below). Does this make any sense to you?

```nslookup: can't resolve 'etcd-4wdl9zk8cq.etcd.mayastor.svc'
Server:    10.152.183.10
Address 1: 10.152.183.10

nslookup: can't resolve 'etcd-4wdl9zk8cq.etcd.mayastor.svc'
Server:    10.152.183.10
Address 1: 10.152.183.10

nslookup: can't resolve 'etcd-4wdl9zk8cq.etcd.mayastor.svc'
Server:    10.152.183.10
Address 1: 10.152.183.10

nslookup: can't resolve 'etcd-4wdl9zk8cq.etcd.mayastor.svc'
Server:    10.152.183.10
Address 1: 10.152.183.10

nslookup: can't resolve 'etcd-4wdl9zk8cq.etcd.mayastor.svc'
Server:    10.152.183.10
Address 1: 10.152.183.10

nslookup: can't resolve 'etcd-4wdl9zk8cq.etcd.mayastor.svc'

```

**Comment by ivanix1** [comment]
@victor-sudakov  Can i ask a stupid question? Are you running debian OS on bare metal server or on a vm of some sort?
I ask because I also have same problem when trying to run microk8s/1.24 + mayastor on ubuntu 22.04 in a vm managed by multipass (qemu). Pods always pending.
However, if i install microk8s with mayastor in ubuntu os running on bare metal. they all come up running.
But then I hit a known issue in that mayastor take 100% of a cpu.
I suspect  either the vm doesn't have a spare cpu for mayastor,  or, because mayastor does thick-provisioning it conflicts with multipass that use thin-provisioning for the vm storage. 
Hope i don't appear to be hijacking your thread.

**Comment by victor-sudakov** [comment]
@ivanix1 I think it is a smart question. I'm experimenting in AWS EC2 instances, not on bare metal. I wonder if it matters.

**Comment by tiagolobocastro** [comment]
Quite stale and seems like it was not a mayastor issue.
Please reopen if otherwise, thanks!
