### ISSUE TITLE
[Doc Source]: [HOW TO: use spdk NVMe driver in mayastor?]

### ISSUE THREAD

**Issue by MayHuo** [openebs/mayastor#1610]
Hi there,

Is it possible to use SPDK NVMe driver when I use a NVMe SSD to create a diskpool? 
And how to write in diskpool yaml configuration file?

**Comment by tiagolobocastro** [comment]
Hi, yes, you need to use example: pice:///e5:00.0 as the disk pool disk uri.
You'll need to unbind the device from the kernel yourself as we currently don't provide a nice way to do that for users but we've got something in our roadmap to improve this somewhat.

**Comment by MayHuo** [comment]
> Hi, yes, you need to use example: pice:///e5:00.0 as the disk pool disk uri. You'll need to unbind the device from the kernel yourself as we currently don't provide a nice way to do that for users but we've got something in our roadmap to improve this somewhat.

Hi, thanks for your reply
I have tried it follow your guidance and it works

**Comment by orville-wright** [comment]
hey @MayHuo @tiagolobocastro it would be good to show the steps of the solution here...
1. unbinding the device from the kernel
2. the working yaml file 
3. any other key steps

... here in the comments so that there's an explicit history of the solution, for others to see. And then our Docs folks could document this as a working feature that can be manually enabled by other users if needed.

**Comment by tiagolobocastro** [comment]
This has been documented:
https://openebs.io/docs/main/faqs/faqs#how-to-access-nvme-disk-directly-from-userspace-via-pcie-when-creating-a-diskpool
