### ISSUE TITLE
Replica destruction may take a while depending on load and scheme

### ISSUE THREAD

**Issue by jkryl** [openebs/Mayastor#481]
While investigating issue #474 we have found that destruction of a relatively small replica (~5G) can take a minute or two. If we interpolate that to larger replicas then the destruction could take tens of minutes, which seems to be unacceptable. I suspect that what takes a long time is clearing the old data from the volume. Depending on the configuration that can be UNMAP or write zeroes operation. The latter is very time-consuming for sure. A couple of tasks here:

1. find a minimal test case how to reproduce the problem
2. find out what k8s mandates from storage driver in terms of clearing old data from a volume
3. if clearing old data is required, based on limits of SPDK figure out if that could be done asynchronously

**Comment by jonathan-teh** [comment]
The replicas (lvols) are cleared by writing zeroes on destruction as the underlying bdev (whether aio or uring) does not support UNMAP, this was observed while investigating #437.

**Comment by jkryl** [comment]
Assuming we must reset data on volumes when destroying them (let's google an explicit statement somewhere in csi driver doc), the remaining question would be how to do that asynchronously if that is possible to do at all. It will be tricky because we must keep the API consistent. That is, if we destroy the volume and return "done", then list volumes should not list that volume anymore. Or it can list the volume but with a special flag as being destroyed.

Or we make UNMAP work with spdk lvols (those backed by ssd devices and io-uring). That would solve the problem at least for the majority of cases.

**Comment by jonathan-teh** [comment]
UNMAP should be mapped to punch-hole in IORING_OP_FALLOCATE, which requires kernel 5.6.

**Comment by tiagolobocastro** [comment]
what happens if mayastor crashes while it's unmapping/zeroing the lvol, does spdk retry when it starts up again or does it forget about it?

**Comment by jkryl** [comment]
I would say the later one. Though if everything worked except this corner case, I think we could be reasonably satisfied with the solution :-)

**Comment by gila** [comment]
It should not matter what CSI says about the issue. I would be surprised if it does.  We need to ensure we do the right thing and to me, the problem here is that if we were to *not* unmap (or write zeroes) -- any PVC created post destruction can access the data we just destroyed. Clearly, that's not what we want! 

There is any other issue here as well I would think, as the gRPC call is outstanding, it will at some point, timeout?

**Comment by jkryl** [comment]
With @cjones1024 's changes the time that it takes to destroy a replica has significantly decreased now when using unmap. I think it is time to close the ticket. What do you think Colin?

**Comment by cjones1024** [comment]
SPDK itself was modified so that the aio module now supports unmap() and write_zeroes(). This means that unamp() is used if supported by the underlying disk. Even when this is not the case, writing zeroes is now performed entirely within the kernel and is considerably more efficient than the old behavior, in which write_zeroes() was emulated in the spdk upper layer by using ordinary write() calls.

In my test environment, using the old SPDK, zeroing and destroying an lvol would take about around 2.4 seconds per Gigabyte. Using the newly modified spdk, the same operation takes between 5-50 milliseconds independently of the size of the lvol. (If the lvol is aligned to cluster boundaries then the operation takes about 5 milliseconds. If the lvol is not aligned, and partial zeroing is required for clusters that straddle the boundaries, then the operation is somewhat slower and can take up to 50 milliseconds.)

**Comment by cjones1024** [comment]
Agreed this ticket can now be closed.
