### ISSUE TITLE
[introduction/quickstart/deploy-mayastor]: [Add mitigation details for potential error case]

### ISSUE THREAD

**Issue by AntonOfTheWoods** [openebs/mayastor#514]
**Are you reporting an issue with existing content?**
Please describe the error or omission, or your suggestion for improvement.
Please include a link the affected page(s)

https://mayastor.gitbook.io/introduction/quickstart/deploy-mayastor

**Are you proposing new content, or a change to the existing documentation layout or structure?**

Add a warning that if you receive the error:
```
$ kubectl -n mayastor get msn
error: the server doesn't have a resource type "msn"
```
Then the problem may well be that no nodes have sufficient `HugePages`. That is entirely non-obvious given the message. The problem being that the daemonset nodes run with no errors and no suggestion that there is any problem but they do not do what the documentation suggests they will, and they do it *silently*.

**Comment by jkryl** [comment]
I don't think that the error message is a consequence of not having enough of hugepages. The error message says that custom resource definition for msn does not exist and not that there are no msn records. CRD is created when moac (control plane) starts. Likely moac wasn't fully up and running when you ran this command or CRD wasn't created due to an error.

I think that the solution with checking hugepages in init container of mayastor could potentially solve this issue - that is: inform the user that an insufficient number of hugepages is the reason for not starting mayastor.

**Comment by jkryl** [comment]
I will hijack this ticket for the purpose of implementing the enhancement of logging a clear error message and exiting from mayastor when the system does not have at least 512 free huge pages.

**Comment by gila** [comment]
@jkryl The number of required huge pages should not be a magical constant, rather it should be depending on several settings like, for example, the number of cores, the number of buffers, etc.

**Comment by jkryl** [comment]
After discussing this with @gila   we decided that this is too much of a corner case that we try to solve here. k8s will refuse to start mayastor on a node with less than 512 free HPs. This check does not always work because when there is another app consuming hugepages then k8s does not keep with the changes to free HPs (at least not always). We consider this to be a bug in k8s rather than mayastor. So closing the ticket for now.

**Comment by AntonOfTheWoods** [comment]
Hi @jkryl , that's a little disappointing. I opened this ticket basically to suggest that a warning be added to the documentation so that onboarding new users can be easier (if a "fix" couldn't be found anyway). The ticket evolved from there - you hijacked it - and now it is being closed because you decided that the new subject (after hijacking) is not easily fixable. 

While adapting complex systems to unique situations will always involve a little time-wasting, this looks like you are simply dismissing what I felt was a legitimate "gotcha" for people who very rarely have to deal with hugepages. I have worked in company with 10s of thousands of servers and we only rarely had to deal with hugepages. Anyway...

**Comment by jkryl** [comment]
I'm sorry @AntonOfTheWoods I was too much focused on the subject that I brought into the ticket. You are right that the original reason for the ticket is still valid. So I think that we could add something as follows to our documentation:
```
If you don't see any msn records, check that all prerequisites for running mayastor have been met, including hugepage configuration.
```
With that, I'm reassigning the ticket to someone else who can change our documentation. Thanks!
