### ISSUE TITLE
Failed to start mayastornode watcher: Error: connect EHOSTUNREACH

### ISSUE THREAD

**Issue by devopsawy** [openebs/Mayastor#600]

**Comment by GlennBullingham** [comment]
Moving reporter's description of the issue to comments, rather than the issue title.  Moving to "Bug" label, not "Documentation".

Quote:
I just get one online msn node and the others still offline.. please find the list of errors Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}&& (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) && Failed to start mayastornode watcher: Error: connect EHOSTUNREACH 10.96.0.1:443

**Comment by GlennBullingham** [comment]
User's original report content (from #openebs @ kubernetes.slack.com)

Seeking your help in #mayastor openebs solution
https://mayastor.gitbook.io/introduction/quickstart/deploy-mayastor
I have followed all steps and stuck in $ kubectl get msn -n mayastor
I am just getting one online msn node and others still offline
Kindly find logs associated from loki
Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,} --> on all mayastor-csi pods while all pods are up & running with no issue
I have tested other csi-drivers either newer or older with no luck :disappointed:
NAME            STATE     AGE
kube-worker00   offline   24m
kube-worker01   offline   24m
kube-worker02   online    24m

**Comment by GlennBullingham** [comment]
Providing @jkryl 's response from the #openebs slack channel, as it is possibly relevant to both reported cases

Quote:
I suppose that you are testing 0.6 version of images (latest tag). Could you try to restart moac pod and see if it makes any difference? If it does not, could you make sure that you don’t have any firewall rules in your cluster that would prohibit gRPC traffic between MOAC and storage nodes (port 10124)?
