### ISSUE TITLE
CI/CD and Helm help offer

### ISSUE THREAD

**Issue by jtcarnes** [openebs/mayastor#996]
Deploying storage on my home cluster, was pointed in yalls way. Looks very interesting.

Your helm chart seems to indicate that its not yet ready and there doesn't seem to be any cicd for this open source repo.

Are those things yall could use a hand in? And if so, do you have a roadmap I could contribute to?

**Comment by gila** [comment]
Hi @jtcarnes, we have actually. We run it on Jenkins instead of the perhaps more expected actions system from GH. Having some look into the helm charts would be great. I do not have much (read any) experience with them myself as I use them for my personal deployments terraform. Perhaps @kmova has a bit more info about how we use helm charts.
